# External imports
from sqlmodel import Field, Session, SQLModel, create_engine, select
import datetime
from decimal import Decimal

# Internal imports
from utils import current_timestamp

class CollectionBase(SQLModel):
    title: str = Field(index=True, unique=True)
    description: str | None = Field(default=None)
    privacy: str

class Collections(CollectionBase, table=True):
    id: int | None = Field(default=None, primary_key=True) # Id is optional because it is generated by the database (just leave it like that)
    created_by: int = Field(foreign_key="users.id")
    created_at: Decimal = Field(default_factory=current_timestamp)
    updated_at: Decimal = Field(default_factory=current_timestamp)
    deleted_at: Decimal | None = Field(default=None)

class CollectionCreate(CollectionBase):
    pass

class CollectionResponse(CollectionBase):
    id: int
    thumbnail_location: str | None
    created_by: int
    created_at: Decimal
    updated_at: Decimal

class UploadCollectionLink(SQLModel, table=True):
    upload_id: int | None = Field(default=None, foreign_key="uploads.id", primary_key=True)
    collection_id: int | None = Field(default=None, foreign_key="collections.id", primary_key=True)
    created_at: Decimal = Field(default_factory=current_timestamp)
    created_by: int = Field(foreign_key="users.id")