# External imports
from sqlmodel import Field, SQLModel
from decimal import Decimal

# Internal imports
from utils import current_timestamp

class FileBase(SQLModel):
    upload_id: int = Field(foreign_key="uploads.id")
    original_filename: str
    generated_filename: str
    file_size: int
    file_mime: str
    file_ext: str # Example: 'png'
    created_by: int = Field(foreign_key="users.id")
    
class Files(FileBase, table=True):
    id: int | None = Field(default=None, primary_key=True) # Id is optional because it is generated by the databse (just leave it like that)
    created_at: Decimal = Field(default_factory=current_timestamp)
    deleted_at: Decimal | None = Field(default=None)

class FileCreate(FileBase):
    pass

class FileResponse(FileBase):
    id: int
    created_at: Decimal